name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2.4.0

      - name: Install Node
        uses: actions/setup-node@v3.0.0
        with:
          node-version: 16

      - run: npm ci

      - run: npm run package

      - uses: ./

      - run: npm run markdownlint

      - uses: ./
        if: success() || failure()
        with:
          action: remove

  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [16, 17]

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2.4.0

      - name: Install Node
        uses: actions/setup-node@v3.0.0
        with:
          node-version: ${{ matrix.node }}

      - run: npm ci

      - run: npm run lint

      - run: npm run build

      - run: npm test

      - run: npm run package
        if: ${{ matrix.node != 17 }}

      - run: export NODE_OPTIONS=--openssl-legacy-provider && npm run package
        if: ${{ matrix.node == 17 }}
